### ISSUE TITLE
Add category field and the action fields are overlapping in manage category of admin page

### ISSUE THREAD

**Issue by ShresthaPriya** [12sonam/FreshPicks#10]
While directing to the manage category page, the add category field and the edit action fields are overlapping. May be you can try putting them both in a same container and add some margin and padding and make it responsive. The cross/cancel sign should be on the main container. 

![image](https://github.com/12sonam/FreshPicks/assets/119417756/3056277a-0ed9-4fec-84cb-b0f647463947)

**Comment by Elizasthaaa** [comment]
We organized the "add category" and "edit" fields into one box in the HTML code to prevent them from overlapping. Then, in the CSS, we added space around this box with margins and padding. To keep the close button fixed in the top-right corner, we used CSS properties like position: absolute;, top, and right. These changes improve the layout and make the page more user-friendly.

Before fixing the issue:
![before](https://github.com/12sonam/FreshPicks/assets/119391309/2a53523c-b822-452f-bfb5-fd5848f1d4ce)
After fixing the issue:
![after](https://github.com/12sonam/FreshPicks/assets/119391309/9a0329ce-8a35-4533-b5f3-94540cdb4269)
