### ISSUE TITLE
In admin dashboard total number of customer is not showing in customer page.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#22]
Total number of Customer is showing hundred but there are only 5-6 customer stored in the database. So correct the numbering according to database.

**Comment by Timalcnabibek** [comment]
The problem of not showing customer count is now solved. Customer count is now showing. Before the bug was solved, it looked like this where the total number of customers was 100 which was set manually rather than dynamically.
![image](https://github.com/12sonam/FreshPicks/assets/120554874/85836a54-a993-4661-8a18-21e948b432ff)


After fixing the bug, the total number of customer is showing.

![image](https://github.com/12sonam/FreshPicks/assets/120554874/258b0b37-813c-4696-9107-2f67e5135ed7)
