### ISSUE TITLE
Product information is not showing in update page  input fields for product in admin dashboard .

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#27]
If any problem go through the bug report.

**Comment by Timalcnabibek** [comment]
The Products are now showing in the Product table. The issue is solved.

Before solving the issue the update page did not use to contain the information of the selected products in the input field.

![image](https://github.com/12sonam/FreshPicks/assets/120554874/437f714a-e887-434a-8730-0c1475da6bd0)



but after solving the issue, we could see the selected product's information in the text fields.





![image](https://github.com/12sonam/FreshPicks/assets/120554874/105df364-0f95-4cc2-8e62-d9d56e8220fd)
