### ISSUE TITLE
In farmer dashboard inside the product page product details should be display when clicked to update button.

### ISSUE THREAD

**Issue by Srijalshakya** [12sonam/FreshPicks#32]
if any problem go through the bug report.

**Comment by MaskeyRiddhi** [comment]
I've modified the function in the delprods.html file to update the product by including productName, price, and description, rather than just the productid. Additionally, I've implemented an event listener on the update button to fetch and display the data in the product form. The category field has been removed since it cannot be updated through the product form. 
Before the changes: 
![image](https://github.com/12sonam/FreshPicks/assets/119106952/e93bf048-a933-41a6-8515-e14f5586bad2)
After the changes:
![image](https://github.com/12sonam/FreshPicks/assets/119106952/81442e2b-821d-42fd-99ad-4c93dfc82a82)
